version: '3.8'

services:
  backend:
    # depends_on:
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "4000:4000"



  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
    
    ports:
      - "3000:3000"

  nginx:
        depends_on:
          - backend
          - frontend
        restart: always
        build:
            context: ./nginx
        ports:
            - "81:81"
volumes: 
  db:

networks:
  backend:
  frontend: